name: Run unit and integration tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test-linux:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8 ]
        conda-version: [release]
        include:
          - python-version: 3.9
            conda-version: canary
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Set Conda-Canary
        if: matrix.conda-version == 'canary'
        run: |
          conda install -y -c conda-canary conda

      - name: Source Scripts
        run: |
          source ci/azurepipelines/install_conda_build_test_deps
          pip install --no-deps .
          conda info -a
          source ci/azurepipelines/setup_pytest_replay

      - name: Run Serial tests
        run: |
          conda install conda-verify -y
          pytest --color=yes -vv -n 0 --basetemp /tmp/cb_serial --cov conda_build --cov-report xml -m "serial" tests --test-run-title="Linux-SerialTests"





